services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@db:3306/copart_db
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: copart_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
